# Generated by Django 5.0.3 on 2024-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Network',
            new_name='network',
        ),
        migrations.AlterField(
            model_name='show',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
